### ISSUE TITLE
test orm

### ISSUE THREAD

**Issue by francescobianco** [fmassei/pqwe#1]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by fmassei** [comment]
First of all, thank you for your support and the star!

I took a quick look at your project and I'm positively sure that pqwe and moldable can work together nicely, with no extra code needed.

pqwe doesn't deal with databases at all (even if it provides a couple of database connectors), so each user can choose his preferred way to write the Models, and this of course also includes ORMs like doctrine or moldable. This is a design choice taken from the start, aimed to simplify integrations with old codes and other packages.

If you find any problem integrating the two let me know.

Unfortunately, I don't think I will be able to contribute to your project on your side: my experience on ORMs is almost zero (I used one once or twice in my entire life), so I can't see how I could be of any help.
Anyway, I'm starring your project: the next time I need an ORM, I'll give yours a try.

**Comment by francescobianco** [comment]
@fmassei Please, could you install the library and give me a feedback if there is something wrong?

**Comment by fmassei** [comment]
I did, it worked fine.

Note that you have a couple of errors in the README.md:
- in the first example a typo on "usernane", is spelled wrong.
- in the third the parentheses don't match, the last "));" should be "]);".
- also in the third, "$db::DATE" doesn't work, I had to remove that field.

Except for that the provided examples work.

**Comment by francescobianco** [comment]
@fmassei if you want I have deployed a new version 0.0.47! 
Did you seriously consider the possibility of including Moldable in PQWE through composer.json?

**Comment by fmassei** [comment]
@francescobianco thank you for the update.
As I told you, pqwe doesn't use or need any type of persistent storage, databases included. I'm sure moldable is a wonderful tool, but in this case it's of no use.
